# Generated by Django 6.1.2 on 2026-10-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='token',
            new_name='token_hash',
        ),
        migrations.AddField(
            model_name='invitation',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
